from automata.fa.dfa import DFA
# from transitiondfa import transitionsdfa
from visual_automata.fa.dfa import VisualDFA

identifierDfa=VisualDFA(
    states={"start","q1","error","q2"},
    input_symbols={ "[a-z]","[A-Z]","[0-9]","Symbols","_",";"},
    transitions={
        "start":
            {
            "[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"q1",
             "Symbols":"error",
             "_":"error",
             ";":"error"
             },
        "q1":
            {"[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"q1",
             "Symbols":"error",
             "_":"q1",
             ";":"q2"
             },
        "q2":
            {"[a-z]":"error",
             "[A-Z]":"error",
             "[0-9]":"error",
             "Symbols":"error",
             "_":"error",
             ";":"error"
             },   
        "error":
            {"[a-z]":"error",
             "[A-Z]":"error",
             "[0-9]":"error",
             "Symbols":"error",
             "_":"error",
             ";":"error"
             },    
            },
    initial_state="start",
    final_states={"q2"}  
)
dfa_string = VisualDFA(
    states={"q0","q1","q2","q3","error"},
    input_symbols={"'","ac",";"},
    transitions={
        "q0":{"'":"q1","ac":"error",";":"error"},
        "q1":{"'":"q2","ac":"q1",";":"q2"},
        "q2":{"'":"q0","ac":"error",";":"q3"},
        "q3":{"'":"error","ac":"error",";":"error"},
        "error":{"'":"error","ac":"error",";":"error"},
    },
    initial_state="q0",
    final_states={"q3"},
)
relationOperators=VisualDFA(
   states = {"q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10", "q11", "error"},
    input_symbols = {"[a-z]", "[A-Z]","[0-9]", "<",">" ,"=", "_", "aoc", ";","."},
    transitions={
    "q0":{"[a-z]":"q1",
          "[A-Z]":"q1",
          "[0-9]":"q2",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"error",
          ".":"error"},
        
    "q1":
        {"[a-z]":"q1",
          "[A-Z]":"q1",
          "[0-9]":"q1",
          "<":"q5",
          ">":"q5", 
          "=":"q6", 
          "_":"q1", 
          "aoc":"error", 
          ";":"error",
          ".":"error"},
    
    "q2":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"q2",
          "<":"q5",
          ">":"q5",
          "=":"q6",
          "_":"error",
          "aoc":"error",
          ";":"error",              
          ".":"q3"
          },
    
    
    "q3":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"q4",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"error",          
          ".":"error"
          },
    
    
    "q4":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"q4",
          "<":"q5",
          ">":"q5",
          "=":"q6",
          "_":"error",
          "aoc":"error",
          ";":"error",
          ".":"error"
          },
    
    "q5":{"[a-z]":"q7",
          "[A-Z]":"q7",
          "[0-9]":"q8",
          "<":"error",
          ">":"error",
          "=":"q6",
          "_":"error",
          "aoc":"error",
          ";":"error",
          ".":"error"},
    
    
    "q6":{"[a-z]":"q7",
          "[A-Z]":"q7",
          "[0-9]":"q8",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"error",
          ".":"error"},
    
    "q7":{"[a-z]":"q7",
          "[A-Z]":"q7",
          "[0-9]":"q7",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"q7",
          "aoc":"error",
          ";":"q11",
          ".":"error"},
    
     "q8":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"q8",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"q11",
          ".":"q9"},
     
       "q9":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"q10",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"error",
          ".":"error"},
       
        "q10":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"q10",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"q11",
          ".":"error"},
       
    "q11":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"error",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"error",
          ".":"error"},
    
    "error":{"[a-z]":"error",
          "[A-Z]":"error",
          "[0-9]":"error",
          "<":"error",
          ">":"error",
          "=":"error",
          "_":"error",
          "aoc":"error",
          ";":"error",
          ".":"error"},
    
    },
    initial_state="q0",
    final_states={"q11"},
)
mathematicalOperators=VisualDFA( 
      states={"q0","q1","q2","q3","q4","q5","q6","q7","q8","q9","error","end"},
      input_symbols={"[a-z]", "[A-Z]","[0-9]", "aoc", ";",".","[+|-|/|*]","_"},
      transitions={
        "q0":{"[a-z]":"q1",
              "[A-Z]":"q1",
              "[0-9]":"q2",
              ".":"error",
              ";":"error",
              "aoc":"error",
              "[+|-|/|*]":"error",
              "_":"q1"
              },
        "q1":{"[a-z]":"q1",
              "[A-Z]":"q1",
              "[0-9]":"q1",
              ".":"error",
              ";":"error",
              "aoc":"error",
              "[+|-|/|*]":"q5",
              "_":"q1"
              },
        "q2":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"q2",
              ".":"q3",
              ";":"error",
              "aoc":"error",
              "[+|-|/|*]":"q5",
              "_":"error"
              },
        "q3":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"q4",
              ".":"error",
              ";":"error",
              "aoc":"error",
              "[+|-|/|*]":"error",
              "_":"error"
              },
        "q4":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"q4",
              ".":"error",
              ";":"error",
              "aoc":"error",
              "[+|-|/|*]":"q5",
              "_":"error"
              },
        "q5":{"[a-z]":"q6",
              "[A-Z]":"q6",
              "[0-9]":"q7",
              ".":"error",
              ";":"error",
              "aoc":"error",
              "[+|-|/|*]":"error",
              "_":"error"
              },
        "q6":{"[a-z]":"q6",
              "[A-Z]":"q6",
              "[0-9]":"q6",
              ".":"error",
              ";":"end",
              "aoc":"error",
              "[+|-|/|*]":"q5",
              "_":"q6"
              },
        "q7":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"q7",
              ".":"q8",
              ";":"end",
              "aoc":"error",
              "[+|-|/|*]":"q5",
              "_":"error"
              },
        "q8":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"q9",
              ".":"error",
              ";":"error",
              "aoc":"error",
              "[+|-|/|*]":"error",
              "_":"error"
              },
        "q9":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"q9",
              ".":"error",
              ";":"end",
              "aoc":"error",
              "[+|-|/|*]":"q5",
              "_":"error"
              },
        "end":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"error",
              ".":"error",
              ";":"end",
              "aoc":"error",
              "[+|-|/|*]":"error",
              "_":"error"
              },
        "error":{"[a-z]":"error",
              "[A-Z]":"error",
              "[0-9]":"error",
              ".":"error",
              ";":"end",
              "aoc":"error",
              "[+|-|/|*]":"error",
              "_":"error"
              }
    },
    initial_state="q0",
    final_states={"end"},
)
lineComment=VisualDFA(
    states={"start","q1","error","q2","q3","q4","q5","q6"},
    input_symbols={ "[a-z]","[A-Z]","[0-9]","Symbols","{","}","*"},
    transitions={
        "start":
            {
            "[a-z]":"error",
             "[A-Z]":"error",
             "[0-9]":"error",
             "Symbols":"error",
             "{":"q1",
             "}":"error",
             "*":"error"
             },
        "q1":{
             "[a-z]":"q2",
             "[A-Z]":"q2",
             "[0-9]":"q2",
             "Symbols":"q2",
             "{":"q2",
             "}":"q5",
             "*":"q3"
             },
         "q2":{
             "[a-z]":"q2",
             "[A-Z]":"q2",
             "[0-9]":"q2",
             "Symbols":"q2",
             "{":"q2",
             "}":"q5",
             "*":"q2"
             },
        "q3":{
             "[a-z]":"q3",
             "[A-Z]":"q3",
             "[0-9]":"q3",
             "Symbols":"q3",
             "{":"q3",
             "}":"q3",
             "*":"q4"
             },
      "q4":{
            "[a-z]":"q3",
            "[A-Z]":"q3",
            "[0-9]":"q3",
            "Symbols":"q3",
            "{":"q3",
            "}":"q6",
            "*":"q4"
            },
      "q5":
            {
            "[a-z]":"q2",
            "[A-Z]":"q2",
            "[0-9]":"q2",
            "Symbols":"q2",
            "{":"q2",
            "}":"q5",
            "*":"q2"
             }, 
      "q6":
            {
            "[a-z]":"q3",
            "[A-Z]":"q3",
            "[0-9]":"q3",
            "Symbols":"q3",
            "{":"q3",
            "}":"q3",
            "*":"q3"
             },  
       
        "error":
            {
            "[a-z]":"error",
            "[A-Z]":"error",
            "[0-9]":"error",
            "Symbols":"error",
            "{":"error",
            "}":"error",
            "*":"error"
             },    
            },
    initial_state="start",
    final_states={"q5","q6"}  
)