from automata.fa.dfa import DFA
# from transitiondfa import transitionsdfa
from visual_automata.fa.dfa import VisualDFA

identifierDfa=VisualDFA(
    states={"start","q1","dead","q2"},
    input_symbols={ "[a-z]","[A-Z]","[0-9]","Symbols","_",";"},
    transitions={
        "start":
            {
            "[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"q1",
             "Symbols":"dead",
             "_":"dead",
             ";":"dead"
             },
        "q1":
            {"[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"q1",
             "Symbols":"dead",
             "_":"q1",
             ";":"q2"
             },
        "q2":
            {"[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"dead",
             "Symbols":"dead",
             "_":"dead",
             ";":"dead"
             },   
        "dead":
            {"[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"dead",
             "Symbols":"dead",
             "_":"dead",
             ";":"dead"
             },    
            },
    initial_state="start",
    final_states={"q2"}  
)
dfa_string = VisualDFA(
    states={"q0","q1","q2","q3","dead"},
    input_symbols={"'","ac",";"},
    transitions={
        "q0":{"'":"q1","ac":"dead",";":"dead"},
        "q1":{"'":"q2","ac":"q1",";":"q2"},
        "q2":{"'":"q0","ac":"dead",";":"q3"},
        "q3":{"'":"dead","ac":"dead",";":"dead"},
        "dead":{"'":"dead","ac":"dead",";":"dead"},
    },
    initial_state="q0",
    final_states={"q3"},
)
relationOperators=VisualDFA(
   states = {"q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10", "q11", "dead"},
    input_symbols = {"[a-z]", "[A-Z]","[0-9]", "<",">" ,"=", "_", "aoc", ";","."},
    transitions={
    "q0":{"[a-z]":"q1",
          "[A-Z]":"q1",
          "[0-9]":"q2",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",
          ".":"dead"},
        
    "q1":
        {"[a-z]":"q1",
          "[A-Z]":"q1",
          "[0-9]":"q1",
          "<":"q5",
          ">":"q5", 
          "=":"q6", 
          "_":"q1", 
          "aoc":"dead", 
          ";":"dead",
          ".":"dead"},
    
    "q2":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"q2",
          "<":"q5",
          ">":"q5",
          "=":"q6",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",              
          ".":"q3"
          },
    
    
    "q3":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"q4",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",          
          ".":"dead"
          },
    
    
    "q4":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"q4",
          "<":"q5",
          ">":"q5",
          "=":"q6",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",
          ".":"dead"
          },
    
    "q5":{"[a-z]":"q7",
          "[A-Z]":"q7",
          "[0-9]":"q8",
          "<":"dead",
          ">":"dead",
          "=":"q6",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",
          ".":"dead"},
    
    
    "q6":{"[a-z]":"q7",
          "[A-Z]":"q7",
          "[0-9]":"q8",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",
          ".":"dead"},
    
    "q7":{"[a-z]":"q7",
          "[A-Z]":"q7",
          "[0-9]":"q7",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"q7",
          "aoc":"dead",
          ";":"q11",
          ".":"dead"},
    
     "q8":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"q8",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"q11",
          ".":"q9"},
     
       "q9":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"q10",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",
          ".":"dead"},
       
        "q10":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"q10",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"q11",
          ".":"dead"},
       
    "q11":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"dead",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",
          ".":"dead"},
    
    "dead":{"[a-z]":"dead",
          "[A-Z]":"dead",
          "[0-9]":"dead",
          "<":"dead",
          ">":"dead",
          "=":"dead",
          "_":"dead",
          "aoc":"dead",
          ";":"dead",
          ".":"dead"},
    
    },
    initial_state="q0",
    final_states={"q11"},
)
mathematicalOperators=VisualDFA( 
      states={"q0","q1","q2","q3","q4","q5","q6","q7","q8","q9","dead","end"},
      input_symbols={"[a-z]", "[A-Z]","[0-9]", "aoc", ";",".","[+|-|/|*]","_"},
      transitions={
        "q0":{"[a-z]":"q1",
              "[A-Z]":"q1",
              "[0-9]":"q2",
              ".":"dead",
              ";":"dead",
              "aoc":"dead",
              "[+|-|/|*]":"dead",
              "_":"q1"
              },
        "q1":{"[a-z]":"q1",
              "[A-Z]":"q1",
              "[0-9]":"q1",
              ".":"dead",
              ";":"dead",
              "aoc":"dead",
              "[+|-|/|*]":"q5",
              "_":"q1"
              },
        "q2":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"q2",
              ".":"q3",
              ";":"dead",
              "aoc":"dead",
              "[+|-|/|*]":"q5",
              "_":"dead"
              },
        "q3":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"q4",
              ".":"dead",
              ";":"dead",
              "aoc":"dead",
              "[+|-|/|*]":"dead",
              "_":"dead"
              },
        "q4":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"q4",
              ".":"dead",
              ";":"dead",
              "aoc":"dead",
              "[+|-|/|*]":"q5",
              "_":"dead"
              },
        "q5":{"[a-z]":"q6",
              "[A-Z]":"q6",
              "[0-9]":"q7",
              ".":"dead",
              ";":"dead",
              "aoc":"dead",
              "[+|-|/|*]":"dead",
              "_":"dead"
              },
        "q6":{"[a-z]":"q6",
              "[A-Z]":"q6",
              "[0-9]":"q6",
              ".":"dead",
              ";":"end",
              "aoc":"dead",
              "[+|-|/|*]":"q5",
              "_":"q6"
              },
        "q7":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"q7",
              ".":"q8",
              ";":"end",
              "aoc":"dead",
              "[+|-|/|*]":"q5",
              "_":"dead"
              },
        "q8":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"q9",
              ".":"dead",
              ";":"dead",
              "aoc":"dead",
              "[+|-|/|*]":"dead",
              "_":"dead"
              },
        "q9":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"q9",
              ".":"dead",
              ";":"end",
              "aoc":"dead",
              "[+|-|/|*]":"q5",
              "_":"dead"
              },
        "end":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"dead",
              ".":"dead",
              ";":"end",
              "aoc":"dead",
              "[+|-|/|*]":"dead",
              "_":"dead"
              },
        "dead":{"[a-z]":"dead",
              "[A-Z]":"dead",
              "[0-9]":"dead",
              ".":"dead",
              ";":"end",
              "aoc":"dead",
              "[+|-|/|*]":"dead",
              "_":"dead"
              }
    },
    initial_state="q0",
    final_states={"end"},
)
lineComment=VisualDFA(
    states={"start","q1","dead","q2","q3","q4","q5","q6"},
    input_symbols={ "[a-z]","[A-Z]","[0-9]","Symbols","{","}","*"},
    transitions={
        "start":
            {
            "[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"dead",
             "Symbols":"dead",
             "{":"q1",
             "}":"dead",
             "*":"dead"
             },
        "q1":{
             "[a-z]":"q2",
             "[A-Z]":"q2",
             "[0-9]":"q2",
             "Symbols":"q2",
             "{":"q2",
             "}":"q5",
             "*":"q3"
             },
         "q2":{
             "[a-z]":"q2",
             "[A-Z]":"q2",
             "[0-9]":"q2",
             "Symbols":"q2",
             "{":"q2",
             "}":"q5",
             "*":"q2"
             },
        "q3":{
             "[a-z]":"q3",
             "[A-Z]":"q3",
             "[0-9]":"q3",
             "Symbols":"q3",
             "{":"q3",
             "}":"q3",
             "*":"q4"
             },
      "q4":{
            "[a-z]":"q3",
            "[A-Z]":"q3",
            "[0-9]":"q3",
            "Symbols":"q3",
            "{":"q3",
            "}":"q6",
            "*":"q4"
            },
      "q5":
            {
            "[a-z]":"q2",
            "[A-Z]":"q2",
            "[0-9]":"q2",
            "Symbols":"q2",
            "{":"q2",
            "}":"q5",
            "*":"q2"
             }, 
      "q6":
            {
            "[a-z]":"q3",
            "[A-Z]":"q3",
            "[0-9]":"q3",
            "Symbols":"q3",
            "{":"q3",
            "}":"q3",
            "*":"q3"
             },  
       
        "dead":
            {
            "[a-z]":"dead",
            "[A-Z]":"dead",
            "[0-9]":"dead",
            "Symbols":"dead",
            "{":"dead",
            "}":"dead",
            "*":"dead"
             },    
            },
    initial_state="start",
    final_states={"q5","q6"}  
)
consAssignment=VisualDFA(
    states={"start","q1","dead","q2","q3","q4","q5","q6","q7"},
    input_symbols={ "[a-z]","[A-Z]","[0-9]","aoc","=","_",";",".","-"},
    transitions={
        "start":
            {
            "[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"dead",
             "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"dead"
             },
        "q1":{
             "[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"q1",
             "aoc":"dead",
             "=":"q2",
             "_":"q1",
             ";":"dead",
             ".":"dead",
             "-":"dead"
             },
         "q2":{
             "[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"q3",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"q7"
             },
      "q7":{
             "[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"q3",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"dead"
             },
        "q3":{
             "[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"q3",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"q4",
             ".":"q5",
             "-":"dead"
             },
      "q4":{
            "[a-z]":"dead",
            "[A-Z]":"dead",
            "[0-9]":"dead",
             "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"dead"
            },
        "q5":{
             "[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"q6",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
              "-":"dead"
             },
         "q6":{
             "[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"q6",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"q4",
             ".":"dead",
             "-":"dead"
             },
        "dead":
            {
              "[a-z]":"dead",
            "[A-Z]":"dead",
            "[0-9]":"dead",
             "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"dead"
             },    
            },
    initial_state="start",
    final_states={"q4"}  
)
varAssignment=VisualDFA(
    states={"start","q1","dead","q2","q3","q4","q5","q6","q7","q8","end"},
    input_symbols={ "[a-z]","[A-Z]","[0-9]","aoc","=","_",";",".","-","[+|/|*]"},
    transitions={
        "start":
            {
             "[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"dead",
             "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"dead",
             "[+|/|*]":"dead"
             },
        "q1":{
             "[a-z]":"q1",
             "[A-Z]":"q1",
             "[0-9]":"q1",
             "aoc":"dead",
             "=":"q2",
             "_":"q1",
             ";":"dead",
             ".":"dead",
             "-":"dead",
             "[+|/|*]":"dead"
             },
         "q2":{
             "[a-z]":"q7",
             "[A-Z]":"q7",
             "[0-9]":"q4",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"q3",
             "[+|/|*]":"dead"
             },
        "q3":{
            "[a-z]":"q7",
             "[A-Z]":"q7",
             "[0-9]":"q4",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"dead",
             "[+|/|*]":"dead"
             },
      "q4":{
            "[a-z]":"dead",
            "[A-Z]":"dead",
            "[0-9]":"q4",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"q5",
             "-":"dead",
             "[+|/|*]":"dead"
            },
        "q5":{
             "[a-z]":"dead",
            "[A-Z]":"dead",
            "[0-9]":"q6",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "-":"dead",
             "[+|/|*]":"dead"
             },
         "q6":{
             "[a-z]":"dead",
             "[A-Z]":"dead",
             "[0-9]":"q6",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"end",
             ".":"dead",
              "-":"q3",
             "[+|/|*]":"dead"
             },
      "q7":{
             "[a-z]":"q7",
             "[A-Z]":"q7",
             "[0-9]":"q7",
            "aoc":"dead",
             "=":"dead",
             "_":"q7",
             ";":"end",
             ".":"dead",
              "-":"q3",
             "[+|/|*]":"q8"
             },
       "q8":{
             "[a-z]":"q7",
             "[A-Z]":"q7",
             "[0-9]":"q4",
            "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"end",
             ".":"dead",
              "-":"q3",
             "[+|/|*]":"dead"
             },
       "end":
            {
              "[a-z]":"dead",
            "[A-Z]":"dead",
            "[0-9]":"dead",
             "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "[+|/|*]":"dead",
             "-":"dead",
             },   
        "dead":
            {
              "[a-z]":"dead",
            "[A-Z]":"dead",
            "[0-9]":"dead",
             "aoc":"dead",
             "=":"dead",
             "_":"dead",
             ";":"dead",
             ".":"dead",
             "[+|/|*]":"dead",
             "-":"dead",
             },    
            },
    initial_state="start",
    final_states={"q4"}  
)
relationOperators.show_diagram(view=True)